# Generated by Django 4.2.19 on 2025-03-06 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "module_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("module_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("semester1", "Semester 1"),
                            ("semester2", "Semester 2"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "modules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "professor_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("professor_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "module_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.moduleinstance",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapp.professor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="moduleinstance",
            name="professors",
            field=models.ManyToManyField(to="webapp.professor"),
        ),
    ]
